import React from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import QRCode from "qrcode.react";
import bwipjs from "bwip-js";

// Generate professional invoice PDF
const generateBill = async (c, lab) => {
  const doc = new jsPDF("p", "mm", "a4");

  // ---------------- Header ----------------
  if (lab.logo) {
    doc.addImage(lab.logo, "PNG", 14, 10, 40, 20); // Logo on top-left
  }

  doc.setFontSize(16);
  doc.text(lab.name, 60, 15);
  doc.setFontSize(10);
  doc.text(lab.address, 60, 20);
  doc.text(`Contact: ${lab.contact}`, 60, 25);
  doc.text(`Email: ${lab.email}`, 60, 30);

  doc.setLineWidth(0.5);
  doc.line(14, 35, 196, 35); // separator line

  // ---------------- Patient Info ----------------
  doc.setFontSize(12);
  doc.text(`Invoice: ${c.regNo}`, 14, 42);
  doc.text(
    `Patient: ${c.patient.firstName} ${c.patient.lastName}`,
    14,
    48
  );
  doc.text(`Doctor: ${c.patient.doctor || "SELF"}`, 14, 54);
  doc.text(
    `Date: ${new Date(c.createdAt).toLocaleDateString("en-GB")}`,
    14,
    60
  );

  // ---------------- Tests Table ----------------
  if (c.tests?.length) {
    autoTable(doc, {
      startY: 65,
      head: [["Test Name", "Amount"]],
      body: c.tests.map((t) => [t.name, `Rs.${t.price}`]),
      theme: "grid",
      headStyles: { fillColor: [220, 220, 220] },
    });
  }

  const tableEndY = doc.lastAutoTable?.finalY || 65;

  // ---------------- Total ----------------
  const total = c.payment?.total || 0;
  doc.setFontSize(12);
  doc.text(`Total: Rs.${total}`, 14, tableEndY + 10);
  doc.text(`Paid: Rs.${c.payment?.received || 0}`, 14, tableEndY + 16);
  doc.text(`Discount: Rs.${c.payment?.discount || 0}`, 14, tableEndY + 22);
  doc.text(`Payment Mode: ${c.payment?.mode || "Cash"}`, 14, tableEndY + 28);

  // ---------------- Barcode ----------------
  try {
    const pngBuffer = await bwipjs.toBuffer({
      bcid: "code128",
      text: c.regNo,
      scale: 3,
      height: 10,
      includetext: true,
      textxalign: "center",
    });
    const barcodeBase64 = `data:image/png;base64,${pngBuffer.toString(
      "base64"
    )}`;
    doc.addImage(barcodeBase64, "PNG", 140, 42, 50, 20);
  } catch (err) {
    console.error("Barcode error:", err);
  }

  // ---------------- QR Code ----------------
  const canvas = document.createElement("canvas");
  QRCode.toCanvas(canvas, c.regNo, { width: 80 }, (error) => {
    if (!error) {
      doc.addImage(canvas.toDataURL(), "PNG", 140, tableEndY + 10, 40, 40);
      // ---------------- Footer ----------------
      doc.setFontSize(8);
      doc.text(
        `Generated by ${lab.name} on ${new Date().toLocaleString()}`,
        14,
        280
      );
      doc.text(
        "Thank you for choosing our lab services!",
        14,
        285
      );

      // Save PDF
      doc.save(`Invoice_${c.regNo}.pdf`);
    } else {
      console.error(error);
      doc.save(`Invoice_${c.regNo}.pdf`);
    }
  });
};


// now make bill page when in cases tab i clcik on view bill for certain case it should open this in this
export default function BillButton({ c, lab }) {
  return (
    <button
      className="bg-blue-600 text-white px-3 py-1 rounded-md text-sm"
      onClick={() => generateBill(c, lab)}
    >
      Generate Bill
    </button>
  );
}
